<?php
/**
 * COmanage Registry COU Model
 *
 * Portions licensed to the University Corporation for Advanced Internet
 * Development, Inc. ("UCAID") under one or more contributor license agreements.
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.
 *
 * UCAID licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @link          http://www.internet2.edu/comanage COmanage Project
 * @package       registry
 * @since         COmanage Registry v0.2
 * @license       Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 */
  
class Cou extends AppModel {
  // Define class name for cake
  public $name = "Cou";
  
  // Current schema version for API
  public $version = "1.0";
  
  // Association rules from this model to other models
  public $belongsTo = array(
    // A COU is attached to a CO
    "Co",
    // Also attached to a parent COU
    "ParentCou" => array(
      'className' => 'Cou',
      'foreignKey'=>'parent_id'
    ),
  );
  
  public $hasMany = array(
    "ChildCou" => array(
      'className' => 'Cou',
      'foreignKey'=>'parent_id'
    ),
    // We specifically want to delete CO Departments and Groups that reference this COU
    "CoDepartment" => array('dependent' => true),
    "CoGroup" => array('dependent' => true),
    "CoPersonRole",
    "CoPetition",
    "CoTermsAndConditions",
    "CoEnrollmentFlowAuthzCou" => array(
      'className' => 'CoEnrollmentFlow',
      'foreignKey' => 'authz_cou_id'
    ),
    "CoExpirationPolicyActCou" => array(
      'className' => 'CoExpirationPolicy',
      'foreignKey' => 'act_cou_id'
    ),
    "CoExpirationPolicyCondCou" => array(
      'className' => 'CoExpirationPolicy',
      'foreignKey' => 'cond_cou_id'
    ),
    "CoPipelineSyncCou" => array(
      'className' => 'CoPipeline',
      'foreignKey' => 'sync_cou_id'
    ),
    "CoPipelineReplaceCou" => array(
      'className' => 'CoPipeline',
      'foreignKey' => 'sync_replace_cou_id'
    )
  );

  // Default display field for cake generated views
  public $displayField = "name";
  
  // Default ordering for find operations
  // This breaks with tree behavior, see https://bugs.internet2.edu/jira/browse/CO-230
  //  public $order = array("Cou.name");
  
  // Validation rules for table elements
  public $validate = array(
    'co_id' => array(
      'rule' => 'numeric',
      'required' => true,
      'message' => 'A CO ID must be provided'
    ),
    'name' => array(
      'rule' => array('validateInput',
                      // Colons are not permitted in COU names since they could potentially
                      // cause conflicts with autogenerated CO Group names
                      array('invalidchars' => '<>:')),
      'required' => true,
      'message' => 'A name must be provided'
    ),
    'description' => array(
      'rule' => array('validateInput'),
      'required' => false,
      'allowEmpty' => true
    ),
    'parent_id' => array(
      'content' => array(
        // Strangely, when specified as numeric cake decides to make required = true
        'rule' => '/[0-9]*/',
        'required' => false,
        'allowEmpty' => true,
        'unfreeze' => 'CO'
      )
    ),
    'lft' => array(
      'rule' => 'numeric',
      'required' => false,
      'allowEmpty' => true
    ),
    'rght' => array(
      'rule' => 'numeric',
      'required' => false,
      'allowEmpty' => true
    ),
    'configuration_labels' => array(
      'content' => array(
        'rule' => array('validateConfigurationLabelSyntax'),
        'required' => false,
        'allowEmpty' => true,
        'message' => array('Characters allowed are a-z0-9_- and the comma(,) separator.'),
        'last' => 'true',
      ),
      'exists' => array(
        'rule' => array('validateConfigurationLabelExists'),
        'message' => array('One of the Configuration labels does not exist.'),
        'last' => 'true',
      ),
      'size' => array(
        'rule' => array('maxlength', 1024),
        'message' => array('Max length is 1024 characters.'),
        'last' => 'true',
      ),
    )
  );

  public $actsAs = array('Containable',
                         // TreeBehavior requires beforeDelete/afterDelete, which Changelog will interrupt
                         'Tree' => array('priority' => 4),
                         'Changelog' => array('priority' => 5));

  /**
   * Request-scoped COU tree cache (per model instance).
   *
   * Stores both:
   * - rows: array of find('all') rows for the scoped COU tree
   * - byId: id => Cou row map derived from those rows
   *
   * Keyed by CO ID string.
   *
   * @since  COmanage Registry v4.6.1
   * @var array
   */
  protected $couTreeCache = array();

  /**
   * Cache for cachedPath() results (request-scoped, per model instance).
   *
   * Keyed by (co scope, cou id).
   *
   * @var array
   * @since  COmanage Registry v4.6.1
   */
  protected $couPathCache = array();

  /**
   * Request-scoped cache for allCous() results.
   *
   * @since COmanage Registry v4.6.1
   * @var array
   */
  protected $allCousCache = array();

  /**
   * Sentinel cache key used when no CO scope is supplied.
   * @var string
   * @since  COmanage Registry v4.6.1
   */
  const CACHE_KEY_ALL_SCOPES = '__all__';

  /**
   * Clear request-scoped caches maintained by this model instance.
   *
   * Use this after any operation that may modify the COU tree (create/update/move/delete),
   * or that may change labels/names used in derived results.
   *
   * @return void
   * @since COmanage Registry v4.6.1
   */
  protected function clearRequestCaches() {
    $this->couTreeCache = array();
    $this->couPathCache = array();
    $this->allCousCache = array();
  }

  /**
   * Convert a CO scope to a stable cache key.
   *
   * With the current caching strategy, a CO ID is always required.
   *
   * @param int $coId
   * @return string
   * @since  COmanage Registry v4.6.1
   */
  protected function cacheScopeKey($coId) {
    return (string)(int)$coId;
  }

  /**
   * Ensure the request-scoped COU tree cache is populated for the given CO.
   *
   * @param int $coId
   * @return void
   * @since  COmanage Registry v4.6.1
   */
  protected function ensureCouTreeCache($coId) {
    $coId = (int)$coId;
    $cacheKey = $this->cacheScopeKey($coId);

    if(isset($this->couTreeCache[$cacheKey])) {
      return;
    }

    $args = array();
    $args['conditions']['Cou.co_id'] = $coId;
    $args['conditions']['Cou.cou_id'] = null;
    $args['fields']  = array('Cou.id', 'Cou.name', 'Cou.parent_id', 'Cou.lft', 'Cou.rght', 'Cou.co_id');
    $args['order']   = 'Cou.lft ASC';
    $args['contain'] = false;

    $rows = $this->find('all', $args);

    $byId = array();
    foreach($rows as $row) {
      if(empty($row['Cou']['id'])) {
        continue;
      }
      $byId[(int)$row['Cou']['id']] = $row['Cou'];
    }

    $this->couTreeCache[$cacheKey] = array(
      'rows' => $rows,
      'byId' => $byId
    );
  }

  /**
   * Callback after model save.
   *
   * @since  COmanage Registry v2.0.0
   * @param  Boolean $created True if new model is saved (ie: add)
   * @param  Array $options Options, as based to model::save()
   * @return Boolean True on success
   */
  public function afterSave($created, $options = Array()) {
    // Clear request-scoped caches whenever tree-relevant fields might have changed.
    // Even if this is "just a rename", derived caches like allCous() depend on name.
    $this->clearRequestCaches();

    if($created
      && !empty($this->data['Cou']['id'])
      && !empty($this->data['Cou']['co_id'])) {
      // Run setup for new COU
      $this->setup($this->data['Cou']['co_id'], $this->data['Cou']['id']);
    }

    return true;
  }

  /**
   * Callback after model delete.
   *
   * @return void
   * @since COmanage Registry v4.6.1
   */
  public function afterDelete() {
    $this->clearRequestCaches();
  }

  /**
   * Obtain all COUs within a specified CO.
   *
   * @param  Integer       $coId          CO ID
   * @param  String        $format        Format, one of "names", "ids", or "hash" of id => name
   * @param  Null|Boolean  $isParent      If null retrieve all COUs.
   *                                      If true retrieve all COUs that have children.
   *                                      If false retrieve all COUs that have no Children
   *
   * @return Array List or hash of member COUs, as specified by $format
   * @since  COmanage Registry v0.4
   */
  public function allCous($coId, $format="hash", $isParent=null) {
    $coId = (int)$coId;

    $scopeFlag = is_null($isParent) ? self::CACHE_KEY_ALL_SCOPES : ($isParent ? 'parents' : 'leaves');
    $cacheKey  = $coId . '|' . $format . '|' . $scopeFlag;

    if(isset($this->allCousCache[$cacheKey])) {
      return $this->allCousCache[$cacheKey];
    }

    // Reuse the request-scoped cached tree (single query per request/coId).
    $rows = $this->cachedCouTree($coId);

    if(empty($rows)) {
      return $this->allCousCache[$cacheKey] = array();
    }

    list($byIdName, $parentIds) = $this->extractNamesAndParentIds($rows);

    if(!is_null($isParent) && !empty($parentIds)) {
      $byIdName = $this->filterByParent($byIdName, $parentIds, (bool)$isParent);
    }

    // Match previous behavior: sort by name ASC.
    asort($byIdName, SORT_STRING);

    return $this->allCousCache[$cacheKey] = $this->formatCouList($byIdName, $format);
  }

  /**
   * Extract an id => name map and the set of parent ids from a tree result set.
   *
   * @param array $rows
   * @return array array($byIdName, $parentIds)
   * @since  COmanage Registry v4.6.1
   */
  protected function extractNamesAndParentIds(array $rows) {
    $byIdName  = array();
    $parentIds = array();

    foreach($rows as $row) {
      if(empty($row['Cou']['id'])) {
        continue;
      }

      $cid = (int)$row['Cou']['id'];
      $byIdName[$cid] = (string)($row['Cou']['name'] ?? '');

      if(!empty($row['Cou']['parent_id'])) {
        $parentIds[(int)$row['Cou']['parent_id']] = true;
      }
    }

    return array($byIdName, $parentIds);
  }

  /**
   * Keep only the COUs that are (or are not) parents.
   *
   * @param array $byIdName id => name map
   * @param  array $parentIds set of parent ids (id => true)
   * @param  bool  $keepParents true to keep parents, false to keep leaves
   * @return array
   * @since  COmanage Registry v4.6.1
   */
  protected function filterByParent(array $byIdName, array $parentIds, $keepParents) {
    $filtered = array();

    foreach($byIdName as $cid => $name) {
      $isParent = isset($parentIds[(int)$cid]);
      if($keepParents === $isParent) {
        $filtered[$cid] = $name;
      }
    }

    return $filtered;
  }

  /**
   * Format an id => name map according to the requested output format.
   *
   * @param  array  $byIdName
   * @param  string $format one of 'names', 'ids', or 'hash'
   * @return array
   * @since  COmanage Registry v4.6.1
   */
  protected function formatCouList(array $byIdName, $format) {
    switch($format) {
      case 'names':
        return array_values($byIdName);
      case 'ids':
        return array_keys($byIdName);
      default:
        return $byIdName;
    }
  }

  /**
   * Obtain all COUs i am an approver for
   *
   * @since  COmanage Registry v4.3.0
   * @param  integer CO Person Id
   *
   * @return Array List of COUs i can approver petitions for
   */

  public function approverForCouList($coPersonId) {
    if(!$coPersonId) {
      return array();
    }

    // Use a join to pull enrollment flows where $coPersonId is in the Predefined COU approver group

    $args = array();
    $args['joins'][0]['table'] = 'co_groups';
    $args['joins'][0]['alias'] = 'CoGroup';
    $args['joins'][0]['type'] = 'INNER';
    $args['joins'][0]['conditions'][0] = 'Cou.id=CoGroup.cou_id';
    $args['joins'][1]['table'] = 'co_group_members';
    $args['joins'][1]['alias'] = 'CoGroupMember';
    $args['joins'][1]['type'] = 'INNER';
    $args['joins'][1]['conditions'][0] = 'CoGroupMember.co_group_id=CoGroup.id';
    $args['conditions']['CoGroupMember.co_person_id'] = $coPersonId;
    $args['conditions']['CoGroup.group_type'] = GroupEnum::Approvers;
    $args['conditions'][] = 'CoGroupMember.co_group_member_id IS NULL';
    $args['conditions'][] = 'CoGroup.co_group_id IS NULL';
    $args['conditions'][] = 'Cou.cou_id IS NULL';
    $args['conditions'][] = 'CoGroupMember.deleted IS NOT true';
    $args['conditions'][] = 'CoGroup.deleted IS NOT true';
    $args['conditions'][] = 'Cou.deleted IS NOT true';
    $args['fields'] = array('Cou.id', 'Cou.name');
    $args['contain'] = false;

    $cou_list = $this->find('list', $args);

    return array_keys($cou_list);
  }

  /**
   * Actions before deleting a model.
   *
   * @since  COmanage Registry v0.8
   * @param  boolean Whether this is a cascading delete
   * @return true for the actual delete to happen
   */

  public function beforeDelete($cascade = true) {
    // This delete may change nested set values across the tree; clear request-scoped caches early.
    $this->clearRequestCaches();

    if(!empty($this->id)) {
      // Remove the node from the tree before deleting it
      
      try {
        // removeFromTree appears to generate bad SQL when there is only one item
        // left to remove; for now we just ignore the Exception since it doesn't
        // actually block us from proceeding.
        $this->removeFromTree($this->id);
      }
      catch(Exception $e) {
        
      }
    }
    
    return parent::beforeDelete($cascade);
  }
  
  /**
   * Generates dropdown option list for html for a COU.
   *
   * When a $coId is supplied we serve the result from the cached tree to avoid
   * an extra DB round trip. The previous DB-based path is kept as a fallback.
   *
   * @since  COmanage Registry v0.3
   * @param  integer COU that needs parent options; NULL if new
   * @param  integer CO ID
   * @return Array Array of [id] => [name]
   */

  public function potentialParents($currentCou, $coId) {
    // Fast path: use the cached COU tree for this CO.
    if(!empty($coId)) {
      $byId = $this->cachedCouTree((int)$coId, 'byId');

      if(!empty($byId)) {
        $excluded = array();

        if($currentCou) {
          $excluded[(int)$currentCou] = true;
          foreach($this->descendantIdsFromTree((int)$currentCou, $byId) as $childId) {
            $excluded[$childId] = true;
          }
        }

        $options = array();
        foreach($byId as $id => $row) {
          if(isset($excluded[(int)$id])) {
            continue;
          }
          $options[(int)$id] = (string)($row['name'] ?? '');
        }

        return $options;
      }
    }

    // Fallback: original behavior (DB-backed).
    if($currentCou) {
      // Find this COU and its children
      $childrenArrays = $this->children($currentCou, false, 'id');
      $childrenList = Set::extract($childrenArrays, '{n}.Cou.id');

      // Set up filter to ignore children
      $conditions = array(
        'AND' => array(
          array(
            'NOT' => array(
              array('Cou.id' => $childrenList),
              array('Cou.id' => $currentCou)
            )
          ),
          array(
            array('Cou.co_id' => $coId)
          )
        )
      );
    } else {
      $conditions = array('Cou.co_id' => $coId);
    }

    $args = array();
    $args['conditions'] = $conditions;
    $args['contain'] = false;

    // Create options list all other COUS in CO
    $optionArrays = $this->find('all', $args);
    return Set::combine($optionArrays, '{n}.Cou.id', '{n}.Cou.name');
  }

  /**
   * Return the per-CO request-scoped tree cache entry (rows + byId).
   *
   * @since  COmanage Registry v4.6.1
   * @param  int $coId
   * @return array array('rows' => array, 'byId' => array)
   */
  protected function cachedTreeEntry($coId) {
    $this->ensureCouTreeCache($coId);
    $cacheKey = $this->cacheScopeKey($coId);

    return $this->couTreeCache[$cacheKey];
  }

  /**
   * Return the request-scoped COU tree cache in the desired representation.
   *
   * Modes:
   * - 'rows': array of find('all') rows (Cou => fields)
   * - 'byId': map of couId => Cou row (Cou fields only)
   *
   * @since  COmanage Registry v4.6.1
   * @param  int    $coId
   * @param  string $mode 'rows' or 'byId'
   * @return array
   */
  protected function cachedCouTree($coId, $mode = 'rows') {
    $entry = $this->cachedTreeEntry($coId);

    switch($mode) {
      case 'byId':
        return $entry['byId'];
      case 'rows':
      default:
        return $entry['rows'];
    }
  }

  /**
   * Cached COU path lookup (request-scoped).
   *
   * Returns an array shaped like TreeBehavior::getPath():
   *   array(
   *     array('Cou' => array(...)),
   *     array('Cou' => array(...)),
   *     ...
   *   )
   *
   * This avoids TreeBehavior::getPath() nested-set queries by walking
   * parent_id pointers in memory over the request-scoped cached tree.
   *
   * @since  COmanage Registry v4.6.1
   * @param  int $couId
   * @param  int $coId CO scope (required)
   * @return array
   */
  public function cachedPath($couId, $coId) {
    $couId = (int)$couId;
    $coId  = (int)$coId;

    if($couId <= 0 || $coId <= 0) {
      return array();
    }

    $scopeKey = $this->cacheScopeKey($coId);
    $cacheKey = $scopeKey . '|' . $couId;

    if(isset($this->couPathCache[$cacheKey])) {
      return $this->couPathCache[$cacheKey];
    }

    $byId = $this->cachedCouTree($coId, 'byId');

    if(empty($byId[$couId])) {
      return $this->couPathCache[$cacheKey] = array();
    }

    // Walk parent pointers up to the root, guarding against cycles.
    $chain = array();
    $seen  = array();
    $cur   = $couId;

    while($cur && isset($byId[$cur]) && empty($seen[$cur])) {
      $seen[$cur] = true;
      $chain[] = array('Cou' => $byId[$cur]);

      $cur = !empty($byId[$cur]['parent_id']) ? (int)$byId[$cur]['parent_id'] : 0;
    }

    // Reverse to get root -> leaf
    return $this->couPathCache[$cacheKey] = array_reverse($chain);
  }

  /**
   * Obtain the child COUs of one or more parent COUs (batch expansion).
   *
   * This method loads the COU tree (scoped to a CO) and then performs
   * interval membership tests on nested set (lft/rght) ranges for each requested
   * parent COU.
   *
   * Results are returned as an ID => label hash, where label is either the COU
   * name or its hierarchy path, depending on $includeHierarchy.
   *
   * @since  COmanage Registry v0.3
   * @param  array $parentCouIds
   * @param  bool  $includeParents
   * @param  bool  $includeHierarchy
   * @param  int   $coId CO scope (required)
   * @return array Hash of COU ID => name/path
   */
  public function childCousByIds($parentCouIds, $includeParents = false, $includeHierarchy = false, $coId) {
    if(empty($parentCouIds) || !is_array($parentCouIds)) {
      return array();
    }

    $coId = (int)$coId;
    if($coId <= 0) {
      return array();
    }

    $rootIds = $this->normalizeRootIds($parentCouIds);
    if(empty($rootIds)) {
      return array();
    }

    // Load the COU tree once per request (nested set fields are required)
    $all = $this->cachedCouTree($coId);

    if(empty($all)) {
      return array();
    }

    $byId = $this->cachedCouTree($coId, 'byId');

    $intervals = $this->intervalsForRoots($rootIds, $byId);
    if(empty($intervals)) {
      return array();
    }

    $merged    = $this->mergeIntervals($intervals);
    $buildPath = $this->buildPathFn($byId);

    $ret = array();
    $m = 0;
    $mCount = count($merged);

    // We can scan in lft-order and check membership in the merged intervals
    foreach($all as $row) {
      if(empty($row['Cou']['id'])) {
        continue;
      }

      $cid = (int)$row['Cou']['id'];

      // Skip explicit roots when parents shouldn't be returned
      if(!$includeParents && in_array($cid, $rootIds, true)) {
        continue;
      }

      $lft  = !empty($row['Cou']['lft'])  ? (int)$row['Cou']['lft']  : null;
      $rght = !empty($row['Cou']['rght']) ? (int)$row['Cou']['rght'] : null;
      if($lft === null || $rght === null) {
        continue;
      }

      // Advance past intervals that end before this row starts
      while($m < $mCount && $lft > $merged[$m][1]) {
        $m++;
      }

      if($m < $mCount && $lft >= $merged[$m][0] && $rght <= $merged[$m][1]) {
        $ret[$cid] = $includeHierarchy ? $buildPath($cid) : (string)$row['Cou']['name'];
      }
    }

    // If includeParents is true, ensure roots are present (even if skipped above)
    if($includeParents) {
      foreach($rootIds as $rid) {
        if(!isset($byId[$rid]) || isset($ret[$rid])) {
          continue;
        }
        $ret[$rid] = $includeHierarchy ? $buildPath($rid) : (string)$byId[$rid]['name'];
      }
    }

    return $ret;
  }

  /**
   * Normalize an array of COU IDs into a de-duplicated list of positive ints.
   *
   * @param array $ids
   * @return int[]
   * @since  COmanage Registry v4.6.1
   */
  protected function normalizeRootIds(array $ids) {
    $set = array();
    foreach($ids as $id) {
      if(is_numeric($id) && (int)$id > 0) {
        $set[(int)$id] = true;
      }
    }
    return array_keys($set);
  }

  /**
   * Translate root COU ids into (lft, rght) intervals using a tree map.
   *
   * @param  int[] $rootIds
   * @param  array $byId    id => Cou row map (as returned by cachedTreeById)
   * @return array          List of [lft, rght, rootId]
   * @since  COmanage Registry v4.6.1
   */
  protected function intervalsForRoots(array $rootIds, array $byId) {
    $intervals = array();

    foreach($rootIds as $rid) {
      if(empty($byId[$rid]) || empty($byId[$rid]['lft']) || empty($byId[$rid]['rght'])) {
        continue;
      }
      $intervals[] = array((int)$byId[$rid]['lft'], (int)$byId[$rid]['rght'], $rid);
    }

    return $intervals;
  }

  /**
   * Sort and merge overlapping (lft, rght) intervals.
   *
   * @param  array $intervals List of [lft, rght, ...]
   * @return array            List of [lft, rght] (sorted, non-overlapping)
   * @since  COmanage Registry v4.6.1
   */
  protected function mergeIntervals(array $intervals) {
    usort($intervals, function($a, $b) {
      return $a[0] <=> $b[0];
    });

    $merged = array();
    foreach($intervals as $intvl) {
      $cur = array($intvl[0], $intvl[1]);

      if(empty($merged)) {
        $merged[] = $cur;
        continue;
      }

      $lastIdx = count($merged) - 1;
      if($cur[0] <= $merged[$lastIdx][1]) {
        if($cur[1] > $merged[$lastIdx][1]) {
          $merged[$lastIdx][1] = $cur[1];
        }
      } else {
        $merged[] = $cur;
      }
    }

    return $merged;
  }

  /**
   * Return a closure that memoizes full COU path strings ("root / ... / node").
   *
   * @param  array $byId id => Cou row map
   * @return callable    function(int $id): string
   * @since  COmanage Registry v4.6.1
   */
  protected function buildPathFn(array $byId) {
    $cache = array();

    $build = function($id) use (&$build, &$cache, $byId) {
      if(isset($cache[$id])) {
        return $cache[$id];
      }
      if(empty($byId[$id])) {
        return $cache[$id] = "";
      }

      $name = (string)$byId[$id]['name'];
      $pid  = !empty($byId[$id]['parent_id']) ? (int)$byId[$id]['parent_id'] : 0;

      if(!$pid || empty($byId[$pid])) {
        return $cache[$id] = $name;
      }

      $parentPath = $build($pid);
      return $cache[$id] = ($parentPath !== "" ? ($parentPath . " / " . $name) : $name);
    };

    return $build;
  }

  /**
   * Check if couId is a member of the current CO.
   *
   * Uses the request-scoped tree cache when it has already been populated for
   * the requested CO, to avoid an extra DB query.
   *
   * @since  COmanage Registry v0.3
   * @param  integer $couId COU ID to check
   * @param  integer $coId CO ID
   * @return boolean True if member, false otherwise
   */

  public function isInCo($couId, $coId) {
    $couId = (int)$couId;
    $coId  = (int)$coId;

    if($couId <= 0 || $coId <= 0) {
      return false;
    }

    // Try the CO-scoped cache; if present, membership is implicit.
    $coKey = $this->cacheScopeKey($coId);
    if(isset($this->couTreeCache[$coKey])) {
      return isset($this->couTreeCache[$coKey]['byId'][$couId]);
    }

    // Fallback to a focused DB lookup.
    $args = array();
    $args['conditions']['Cou.id'] = $couId;
    $args['fields'] = array('Cou.id', 'Cou.co_id');
    $args['contain'] = false;

    $couData = $this->find('first', $args);

    return !empty($couData['Cou']['co_id']) && (int)$couData['Cou']['co_id'] === $coId;
  }

  /**
   * Check if couNode is a child of couBranch.
   *
   * Uses the cached tree when available (testing lft/rght containment) to avoid
   * an extra DB call. Falls back to TreeBehavior::children() otherwise.
   *
   * @since  COmanage Registry v0.3
   * @param  integer Head of the branch to be searched
   * @param  integer Node to be looked for
   * @return boolean True if child, false otherwise
   */

  public function isChildCou($couBranch, $couNode) {
    $branch = (int)$couBranch;
    $node   = (int)$couNode;

    if($branch <= 0 || $node <= 0) {
      return false;
    }

    // A node is not a child of itself.
    if($branch === $node) {
      return false;
    }

    // Try any cached CO scopes already loaded for this model instance.
    foreach($this->couTreeCache as $scope) {
      if(empty($scope['byId']) || !is_array($scope['byId'])) {
        continue;
      }

      $byId = $scope['byId'];
      if(!isset($byId[$branch]) || !isset($byId[$node])) {
        continue;
      }

      $bLft  = !empty($byId[$branch]['lft'])  ? (int)$byId[$branch]['lft']  : null;
      $bRght = !empty($byId[$branch]['rght']) ? (int)$byId[$branch]['rght'] : null;
      $nLft  = !empty($byId[$node]['lft'])    ? (int)$byId[$node]['lft']    : null;
      $nRght = !empty($byId[$node]['rght'])   ? (int)$byId[$node]['rght']   : null;

      if($bLft === null || $bRght === null || $nLft === null || $nRght === null) {
        continue;
      }

      // Strict containment (a node is not its own child).
      return ($nLft > $bLft && $nRght < $bRght);
    }

    // Fallback to original behavior.
    $childrenArrays = $this->children($couBranch, false, 'id');
    $childrenList = Set::extract($childrenArrays, '{n}.Cou.id');

    // Check for NULL to avoid warning/error from array_search (See CO-240)
    return $childrenList !== null && array_search($couNode, $childrenList) !== false;
  }

  /**
   * Collect all descendant ids of $rootId from a tree map using nested set
   * intervals when available, falling back to parent_id traversal.
   *
   * @param  int   $rootId
   * @param  array $byId    id => Cou row map
   * @return int[]
   * @since  COmanage Registry v4.6.1
   */
  protected function descendantIdsFromTree($rootId, array $byId) {
    if(empty($byId[$rootId])) {
      return array();
    }

    $lft  = !empty($byId[$rootId]['lft'])  ? (int)$byId[$rootId]['lft']  : null;
    $rght = !empty($byId[$rootId]['rght']) ? (int)$byId[$rootId]['rght'] : null;

    // Preferred path: lft/rght membership.
    if($lft !== null && $rght !== null) {
      $descendants = array();
      foreach($byId as $id => $row) {
        if((int)$id === (int)$rootId) {
          continue;
        }
        $rLft  = !empty($row['lft'])  ? (int)$row['lft']  : null;
        $rRght = !empty($row['rght']) ? (int)$row['rght'] : null;
        if($rLft === null || $rRght === null) {
          continue;
        }
        if($rLft > $lft && $rRght < $rght) {
          $descendants[] = (int)$id;
        }
      }
      return $descendants;
    }

    // Fallback: walk parent_id pointers.
    $descendants = array();
    $stack = array((int)$rootId);
    while(!empty($stack)) {
      $cur = array_pop($stack);
      foreach($byId as $id => $row) {
        if(!empty($row['parent_id']) && (int)$row['parent_id'] === $cur) {
          $descendants[] = (int)$id;
          $stack[] = (int)$id;
        }
      }
    }
    return $descendants;
  }
  
  /**
   * Perform initial setup for a COU.
   *
   * @since  COmanage Registry v2.0.0
   * @param  Integer CO ID
   * @param  Integer COU ID
   * @return Boolean True on success
   */
  
  public function setup($coId, $couId) {
    // Add default groups
    $this->CoGroup->addDefaults($coId, $couId);
    
    return true;
  }

  /**
   * Validates whether a label value belongsTo cm_labels table
   *
   * @param array $check
   *
   * @return bool TRUE if label is valid or FALSE if it is not.
   * @since  COmanage Registry v4.4.0
   */
  public function validateConfigurationLabelExists($check) {
    if (!is_string($check['configuration_labels'])) {
      return false;
    }

    $labelsList = explode(',', $check['configuration_labels']);

    // Check if the label is unique. Since we enabled changelog we need to do it manually
    foreach ($labelsList as $label) {
      $args = array();
      $args['conditions']['ConfigurationLabel.label'] = $label;
      $args['conditions']['ConfigurationLabel.co_id'] = $this->data['Cou']['co_id'];
      $args['contain'] = false;

      $ConfigurationLabel = ClassRegistry::init('ConfigurationLabel');
      $notFoundLabels = $ConfigurationLabel->find('count', $args);

      if($notFoundLabels == 0) {
        return false;
      }
    }

    return true;
  }

  /**
   * Validates whether a label value is syntactically correct.
   * Practically this is the same check we do in cm_labels.
   * Additionally, we allow the comma separator
   *
   * @param array $check
   *
   * @return bool TRUE if label is valid or FALSE if it is not.
   * @since  COmanage Registry v4.4.0
   */
  public function validateConfigurationLabelSyntax($check) {
    if (!is_string($check['configuration_labels'])) {
      return false;
    }
    return preg_match('/^[,a-z0-9_-]{3,}$/', $check['configuration_labels']) === 1;
  }
}
