#!/bin/bash

# COmanage Registry Cache Clearing Script
#
# Portions licensed to the University Corporation for Advanced Internet
# Development, Inc. ("UCAID") under one or more contributor license agreements.
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# UCAID licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @link          http://www.internet2.edu/comanage COmanage Project
# @package       registry
# @since         COmanage Registry v1.0.6
# @license       Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

# We don't use the cake framework to avoid creating new cache files while
# we're trying to clear out the old. First we need to figure out where
# the cache directory is.

CACHEDIR=`dirname $0`"/../../local/tmp/cache"

# Make sure $CACHEDIR exists
if [ ! -d ${CACHEDIR} ]; then
  echo "ERROR: Cache directory does not exist, exiting"
  echo "CACHEDIR="${CACHEDIR}
  exit 1;
fi

# -delete should be available on any
find ${CACHEDIR} -type f -delete

echo "Done clearing caches"
