---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodePipeline pipeline for COmanage Registry container images'

Resources:
  COmanageRegistryPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: comanage-registry
      RestartExecutionOnUpdate: False
      RoleArn: arn:aws:iam::495649616520:role/CILogonCOmanagePipelineRole
      ArtifactStore:
        Type: S3
        Location: cilogon-comanage-registry-pipeline
      Stages:
        - Name: Source
          Actions:
            - Name: RegistrySource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              RunOrder: 1
              Configuration:
                Owner: Internet2
                Repo: comanage-registry
                Branch: main
                OAuthToken: "{{resolve:secretsmanager:COmanageImagePipelineGitHubOAuthToken:SecretString:token}}"
                PollForSourceChanges: "false"
              OutputArtifacts:
                - Name: RegistrySourceArtifact
              Region: us-east-2
              Namespace: SourceVariables
        - Name: BuildNumber
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              RunOrder: 1
              Configuration:
                ProjectName: comanage-registry-buildnumber
              InputArtifacts:
                - Name: RegistrySourceArtifact
              Region: us-east-2
              Namespace: BuildNumberVariables
        - Name: BuildArch
          Actions:
            - Name: BuildAmd64
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              RunOrder: 1
              Configuration:
                ProjectName: comanage-registry-amd64
                EnvironmentVariables: "[{\"name\":\"COMANAGE_REGISTRY_BUILD_NUMBER\",\"value\":\"#{BuildNumberVariables.CODEBUILD_BUILD_NUMBER}\",\"type\":\"PLAINTEXT\"}]"
              InputArtifacts:
                - Name: RegistrySourceArtifact
              Region: us-east-2
              Namespace: BuildAmd64Variables
            - Name: BuildArm64
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              RunOrder: 1
              Configuration:
                ProjectName: comanage-registry-arm64
                EnvironmentVariables: "[{\"name\":\"COMANAGE_REGISTRY_BUILD_NUMBER\",\"value\":\"#{BuildNumberVariables.CODEBUILD_BUILD_NUMBER}\",\"type\":\"PLAINTEXT\"}]"
              InputArtifacts:
                - Name: RegistrySourceArtifact
              Region: us-east-2
              Namespace: BuildArm64Variables
        - Name: BuildManifest
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              RunOrder: 1
              Configuration:
                ProjectName: comanage-registry-manifest
                EnvironmentVariables: "[{\"name\":\"COMANAGE_REGISTRY_BUILD_NUMBER\",\"value\":\"#{BuildNumberVariables.CODEBUILD_BUILD_NUMBER}\",\"type\":\"PLAINTEXT\"}]"
              InputArtifacts:
                - Name: RegistrySourceArtifact
              Region: us-east-2
              Namespace: BuildManifestVariables

Outputs:
  COmanageRegistryPipelineName:
    Value: !Ref COmanageRegistryPipeline
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}::PipelineName"
