---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodeBuild project for COmanage Registry build number'

Resources:
  COmanageRegistryBuildProjectBuildNumber:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: comanage-registry-buildnumber
      Source:
        Type: CODEPIPELINE
        BuildSpec: container/aws/buildspec/aws_buildspec_buildnumber.yml
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:7.0
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: True
        ImagePullCredentialsType: CODEBUILD
      ServiceRole: arn:aws:iam::495649616520:role/CilogonBuildComanagePublicContainerImage
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: arn:aws:kms:us-east-2:495649616520:alias/aws/s3
      BadgeEnabled: False
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: /aws/codebuild/comanage
          StreamName: registry-buildnumber
